export const faqData = [
  {
    question: "What is an AI name generator?",
    answer:
      "An AI name generator uses artificial intelligence to generate unique and creative names for businesses, products, or domains based on provided keywords or preferences.",
  },
  {
    question: "How does an AI name generator work?",
    answer:
      "AI name generators analyze keywords, patterns, and trends using machine learning algorithms to produce name suggestions that are relevant, unique, and creative.",
  },
  {
    question: "Can an AI name generator create domain-specific names?",
    answer:
      "Yes, AI name generators can provide domain-specific names by incorporating keywords and adjusting the output to fit a specific industry or niche.",
  },
  {
    question: "Are the names generated by AI unique?",
    answer:
      "While AI generates creative and often unique names, it's always recommended to check domain availability and trademark registrations to ensure exclusivity.",
  },
  {
    question: "Can AI name generators support multiple languages?",
    answer:
      "Yes, many AI name generators support multiple languages, enabling users to create names that resonate with their target audience in different regions.",
  },
];